### ISSUE TITLE
Exercise 65: Correctly solved exercise produces incorrect output on latest Zig version

### ISSUE THREAD

**Issue by feathecutie** [ratfactor/ziglings#128] opened 2022-08-21 11:51 UTC
On Zig version `0.10.0-dev.3659+e5e6eb983` (master branch from 2022-08-20), exercise 65 produces the following output:
```
----------- Expected this output -----------
A Narcissus loves all Narcissuses. He has room in his heart for: me myself.
----------- but found -----------
A 065_builtins2.Narcissus loves all 065_builtins2.Narcissuses. He has room in his heart for: me myself.
```
This happens on both the self-hosted backend (the default from this version onward) and the old stage1 backend (using `-fstage1`).
This still works correctly on `0.10.0-dev.3633+be2bd5848`, which should just be a day or so older.

**Comment by chrboesch** [comment] 2022-08-21 15:04
On Zig version `0.10.0-dev.3566+a9c4dc84f` the output is:

`----------- Expected this output -----------
A Narcissus loves all Narcissuses. He has room in his heart for: me myself.
----------- but found -----------
A Narcissus loves all (bound fn() anytype)es. He has room in his heart for: me myself.

-----------
`
But I'm not really sure that I solved the exercise in the right way. :thinking:

**Comment by ratfactor** [comment] 2022-08-22 13:13
Ha ha. Wow. Sounds like there as a pretty big change there!

**Comment by chrboesch** [comment] 2022-08-22 14:00
I must correct myself: Have solved the task again and this time everything is correct!

**Comment by ratfactor** [comment] 2022-08-22 16:17
Also leaving this here as something to check against:

https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Upgrade-Guide/

**Comment by chrboesch** [comment] 2022-08-22 19:12
Now compiled with  `0.10.0-dev.3672+cd5a9ba1f` (lbinary download from today 22.08.)
```
----------- Expected this output -----------
A Narcissus loves all Narcissuses. He has room in his heart for: me myself.
----------- but found -----------
A 065_builtins2.Narcissus loves all 065_builtins2.Narcissuses. He has room in his heart for: me myself.
```

and then compiled with `0.10.0-dev.3682+1a32f2a7f` (master branch from today 22.08.)
```
----------- Expected this output -----------
A Narcissus loves all Narcissuses. He has room in his heart for: me myself.
----------- but found -----------
A 065_builtins2.Narcissus loves all 065_builtins2.Narcissuses. He has room in his heart for: me myself.
```
@ratfactor Seems that's your turn. We are only the students. :wink:

**Comment by chrboesch** [comment] 2022-08-22 21:02
I've found out something: It seems that the print function is generating the error. When I ran a simple test program, 
```
const Narcissus = struct {};
var na: Narcissus = Narcissus{};
const T = @TypeOf(na);
try expect(T == Narcissus);
``` 
`All 1 tests passed.`

But when I run
```  
print("{}\n", .{T});
```
I get `test.Narcissus`. 
`test.zig` is the name of the test prog and is obviously prefixed to the type when printing.

**Comment by SeedyROM** [comment] 2022-08-23 20:44
This same change to Zig will also mess up Exercise 80:
```
----------- Expected this output -----------
[Circle(i32): 25,70,15] [Circle(f32): 25.2,71.0,15.7]
----------- but found -----------
[080_anonymous_structs.Circle(i32): 25,70,15] [080_anonymous_structs.Circle(f32): 25.2,71.0,15.7]
```

**Comment by chrboesch** [comment] 2022-08-24 16:09
Now I have opened a Ziglang issue: [ When @TypeOf() is output to stdout, it is prefixed with the filename #12620 ](https://github.com/ziglang/zig/issues/12620)

**Comment by chrboesch** [comment] 2022-08-24 16:22
Ziglang issue was closed: "Working as intended." :thinking:

**Comment by ratfactor** [comment] 2022-08-24 16:32
Intriguing! Thanks for the legwork on this @chrboesch !

**Comment by jecepeda** [comment] 2022-08-28 09:52
Hi there. Do you need any PR to solve this exercise? I'm finding the same problem here

**Comment by ratfactor** [comment] 2022-08-29 21:43
@jecepeda Thanks for asking! I did a fix for this one this weekend, but hadn't committed it yet. I guess I was thinking I would fix some of the others at the same time. But I might as well put up what I've got. :-)

**Comment by ratfactor** [comment] 2022-08-29 22:41
Ha ha, so I went for the "dumb fix" on this and I think that'll be okay.  I also fixed a very misleading hint on this one, but here's the new utility function and comment that I slapped on the end of the exercise to fix this:

```
// NOTE: This exercise did not originally include the function below.
// But a change after Zig 0.10.0 added the source file name to the
// type. "Narcissus" became "065_builtins2.Narcissus".
//
// To fix this, I've added this function to strip the filename from
// the front of the type name in the dumbest way possible. (It returns
// a slice of the type name starting at character 14 (assuming
// single-byte characters).
//
// We'll be seeing @typeName again in Exercise 070. For now, you can
// see that it takes a Type and returns a u8 "string".
fn maximumNarcissism(myType: anytype) []const u8 {
    // Turn '065_builtins2.Narcissus' into 'Narcissus'
    return @typeName(myType)[14..];
}
```

(You can see all of the changes in the above referenced commit.)

**Closed by ratfactor** 2022-08-29 22:41 UTC
